language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - nightly

# matrix:
#   allowed_failures:
#     - julia: 0.7
#     - julia: nightly

notifications:
  email: false
# uncomment the following lines to override the default test script
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --color=yes -e 'using Pkg; Pkg.build()'
    - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'

# necessary to run on new container-based infrastructure
sudo: false
